/// Flutter icons ChatIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ChatIcons
///      fonts:
///       - asset: fonts/ChatIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ChatIcons {
  ChatIcons._();

  static const _kFontFam = 'ChatIcons';
  static const String _kFontPkg = null;

  static const IconData banana = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cheeto = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chip = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ice_cream_cone = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cookies = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData toast = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
